In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
%matplotlib inline
warnings.filterwarnings('ignore')

In [3]:
test = pd.read_csv(r"iris_modified.csv")
test.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
test.shape

(150, 5)

In [5]:
test.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [6]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [7]:
test.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [8]:
X = test.drop(columns=['species'])
# Target variable (y): 'species'
Y = test['species']

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
test['species']=le.fit_transform(test['species'])

In [10]:
test.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [11]:
print(X.shape)
print(Y.shape)

(150, 4)
(150,)


In [12]:
from sklearn.model_selection import train_test_split
 
#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.8,random_state=10) 

#predicting using the RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier

model_RandomForest=RandomForestClassifier(n_estimators=100,random_state=10,
                                        max_depth=30,bootstrap=True, min_samples_leaf = 5)

model_RandomForest.fit(X_train,Y_train)
#fit the model on the data and predict the values
Y_pred=model_RandomForest.predict(X_test)
print(Y_pred)

## Random Forest

In [15]:
rfc=RandomForestClassifier(random_state=42)

In [16]:
param_grid = { 
    'n_estimators': list(range(10, 31)),
    'max_depth': list(range(20, 31)),
    'min_samples_leaf': list(range(5,51)),
    'criterion' :['gini','entropy']
}

In [18]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [42]:
CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 2)
CV_rfc.fit(X_train,Y_train)

GridSearchCV(cv=2, estimator=RandomForestClassifier(random_state=42),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
                                       30],
                         'min_samples_leaf': [5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
                                              15, 16, 17, 18, 19, 20, 21, 22,
                                              23, 24, 25, 26, 27, 28, 29, 30,
                                              31, 32, 33, 34, ...],
                         'n_estimators': [10, 11, 12, 13, 14, 15, 16, 17, 18,
                                          19, 20, 21, 22, 23, 24, 25, 26, 27,
                                          28, 29, 30]})

In [43]:
CV_rfc.best_params_

{'criterion': 'gini',
 'max_depth': 20,
 'min_samples_leaf': 5,
 'n_estimators': 23}

In [44]:
rfc1=RandomForestClassifier(random_state=42, max_features='auto', n_estimators= 200, max_depth=8, criterion='gini')

In [46]:
rfc1.fit(X_train, Y_train)

RandomForestClassifier(max_depth=8, max_features='auto', n_estimators=200,
                       random_state=42)

In [47]:
pred=rfc1.predict(X_test)

In [51]:
print("Accuracy for Random Forest on CV data: ",accuracy_score(Y_test,pred))

Accuracy for Random Forest on CV data:  0.95


In [72]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,pred)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(Y_test,pred))
 
acc=accuracy_score(Y_test, pred)
print("Accuracy of the model: ",acc)

[[41  0  0]
 [ 0 40  1]
 [ 0  5 33]]
Classification report: 
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        41
Iris-versicolor       0.89      0.98      0.93        41
 Iris-virginica       0.97      0.87      0.92        38

       accuracy                           0.95       120
      macro avg       0.95      0.95      0.95       120
   weighted avg       0.95      0.95      0.95       120

Accuracy of the model:  0.95


## Decision Tree

In [75]:
dtr=DecisionTreeRegressor(random_state=42)

In [76]:
param_grid = { 
    'max_depth':list(range(4,8)),
    'min_samples_leaf':[12,6],
    "splitter":['best'],
    'criterion':['entropy']}

tree_clas = DecisionTreeClassifier(random_state=1024)
grid_search = GridSearchCV(estimator=tree_clas, param_grid=param_grid, cv=5, verbose=True)
grid_search.fit(X_train, Y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits


GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=1024),
             param_grid={'criterion': ['entropy'], 'max_depth': [4, 5, 6, 7],
                         'min_samples_leaf': [12, 6], 'splitter': ['best']},
             verbose=True)

In [77]:
final_model = grid_search.best_estimator_
final_model

DecisionTreeClassifier(criterion='entropy', max_depth=4, min_samples_leaf=12,
                       random_state=1024)

In [78]:
tree_clas = DecisionTreeClassifier(criterion='entropy', max_depth=4, min_samples_leaf=6,
                       random_state=1024)
tree_clas.fit(X_train, Y_train)
y_predict = tree_clas.predict(X_test)

In [79]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,y_predict)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(Y_test,y_predict))
 
acc=accuracy_score(Y_test, y_predict)
print("Accuracy of the model: ",acc)

[[10  0  0]
 [ 0 11  2]
 [ 0  0  7]]
Classification report: 
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      0.85      0.92        13
 Iris-virginica       0.78      1.00      0.88         7

       accuracy                           0.93        30
      macro avg       0.93      0.95      0.93        30
   weighted avg       0.95      0.93      0.93        30

Accuracy of the model:  0.9333333333333333


## SVM

In [19]:
params = {
    'kernel':['linear','rbf','poly','sigmoid'],
    'C':[566,79],
    'gamma':['auto','scale','custom'],
    'gamma':[1,0.1,0.01,0.001,0.0001],
    'tol':[7],
    'max_iter':[7],
}
model_svm=SVC()

In [21]:
# perfom Grid Search 
grid_search= GridSearchCV(estimator=model_svm,param_grid=params, cv=5,n_jobs=-1)
grid_search.fit(X_train,Y_train)

GridSearchCV(cv=5, estimator=SVC(), n_jobs=-1,
             param_grid={'C': [566, 79], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['linear', 'rbf', 'poly', 'sigmoid'],
                         'max_iter': [7], 'tol': [7]})

In [22]:
final_model = grid_search.best_estimator_
final_model

SVC(C=566, gamma=1, kernel='linear', max_iter=7, tol=7)

In [23]:
# Training the model
model_svm=SVC(C=566, gamma=1, kernel='linear', max_iter=7, tol=7)
model_svm.fit(X_train, Y_train)
y_pred = model_svm.predict(X_test)

In [24]:
# Training the model
model_svm=SVC(C=566, gamma=1, kernel='linear', max_iter=7, tol=7)
model_svm.fit(X_train, Y_train)
y_pred = model_svm.predict(X_test)

In [25]:
from sklearn.metrics import confusion_matrix,classification_report
cfm=confusion_matrix(Y_test,y_pred)
print(cfm)
print('Classification report:')
print(classification_report(Y_test,y_pred))

[[ 0  0 10]
 [ 0  0 13]
 [ 0  0  7]]
Classification report:
                 precision    recall  f1-score   support

    Iris-setosa       0.00      0.00      0.00        10
Iris-versicolor       0.00      0.00      0.00        13
 Iris-virginica       0.23      1.00      0.38         7

       accuracy                           0.23        30
      macro avg       0.08      0.33      0.13        30
   weighted avg       0.05      0.23      0.09        30

